CREATE TABLE `FTT`.`CLIENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(300) NOT NULL,
  `EMAIL` VARCHAR(500) NOT NULL,
  `ADDRESS` VARCHAR(500) NOT NULL,
  `PHONE` VARCHAR(45) NOT NULL,
  `CELL_PHONE` VARCHAR(45) NOT NULL,
  `DOB` DATETIME NOT NULL,
  `BUDGET` FLOAT NULL,
  `LIMIT` FLOAT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
